Fix open-source build
Summary:
For a while, the build would fail with link errors of this sort:

```
/home/bistro/bistro/../../bistro/bistro/utils/PeriodicPoller.h:138: undefined reference to `folly::ThreadedRepeatingFunctionRunner::add(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, folly::Function<std::chrono::duration<long, std::ratio<1l, 1000l> > ()>, std::chrono::duration<long, std::ratio<1l, 1000l> >)'
```

The core issue was that C++17 makes `noexcept` part of the type-system, but Bistro was being compiled with the `c++14` standard.

This means the compiler would never mark the second  `folly::Function` argument to `add()` as `noexcept` (even when it was in fact `noexcept`), whereas the type signature in `libfolly.so` would actually require the `noexcept`:

```
$ nm -gC /home/install/lib/libfolly.so | grep ThreadedRepeating.*::add
00000000009ea034 T folly::ThreadedRepeatingFunctionRunner::add(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, folly::Function<std::chrono::duration<long, std::ratio<1l, 1000l> > () noexcept>, std::chrono::duration<long, std::ratio<1l, 1000l> >)
```

Reviewed By: Ben0mega

Differential Revision: D16588482

fbshipit-source-id: 17909f0d15661c0c78f505f908d6aa7f0b3e6410