Fuse OSS library `protocol` into `thriftprotocol`
Summary:
I am trying to have Bistro use `find_package(FBThrift CONFIG REQUIRED)` to depend on FBThrift.

Unfortunately, if I do that, and link against `FBThrift::thrift2`, my build fails to link with:

```
.../libprotocol.so.1.0.0: undefined reference to `apache::thrift::CompactProtocolReader::throwBadType(unsigned char)'
.../libprotocol.so.1.0.0: undefined reference to `apache::thrift::CompactProtocolReader::readFieldBeginWithStateMediumSlow(apache::thrift::CompactProtocolReader::StructReadState&, short)'
collect2: error: ld returned 1 exit status
```

This is due to a cyclic dependency between `protocol` (aka Thrift1) and `thriftprotocol` (aka Thrift2). Specifically:
 - `thriftprotocol` explicitly depends on `protocol`
 - `protocol` has an undeclared dep on `thriftprotocol` because it includes the Thrift2 build of the "reflection" interface.

IMO, the "right" fix would be to make `STATIC` all "internal" Thrift libraries, and export only a `libthrift2.so` for external consumption.

However, I don't have cycles to update the entire Thrift build to do this.

Therefore, fusing the circularly dependent libraries is the path of least resistance to letting my project depend on Thrift.

Reviewed By: nlaptev, yfeldblum

Differential Revision: D24685618

fbshipit-source-id: a679d7b3556d1c9859b64f69f98bfa6d48398b1d